### ISSUE TITLE
Add option to allow persisting cookies with no expiry date

### ISSUE THREAD

**Issue by danog** [amphp/http-client-cookies#4]
It would be nice to have an option in the `FileCookieJar` to allow persistance of cookies without an expiry date, since [the current code](https://github.com/amphp/http-client-cookies/blob/master/src/FileCookieJar.php#L105) simply filters out cookies without an expiration date.
Technically, not persisting such cookies is the correct behaviour for HTTP clients, but in certain (scripting) cases this behaviour is still required and useful.

**Comment by kelunik** [comment]
PR welcome. ;-)

**Comment by kelunik** [comment]
Closed via #5.
