### ISSUE TITLE
InMemoryCookieJar should get its real contents

### ISSUE THREAD

**Issue by Bilge** [amphp/http-client-cookies#6]
https://github.com/amphp/http-client-cookies/blob/cd9ccc4d9106fef3f2a2bc10946108dbc62572c5/src/InMemoryCookieJar.php#L55

I don't know what use-case this is intended to serve, but if it's important to rebrand the `ResponseCookie` as a `RequestCookie`, it should at least be optional or a different method or something. This breaks my use-case where I want to copy the cookie from one jar into another.

**Comment by kelunik** [comment]
You can use getAll for that. It returns what's required for making a request.

**Comment by Bilge** [comment]
That probably would be a little easier, but it's still missing a `getByName()` or similar.

**Comment by kelunik** [comment]
Feel free to PR that. ;-)

**Comment by Bilge** [comment]
I think the reason I didn't consider `getAll` is because it does not exist in [the interface](https://github.com/amphp/http-client-cookies/blob/cd9ccc4d9106fef3f2a2bc10946108dbc62572c5/src/CookieJar.php).

**Comment by kelunik** [comment]
No, `getAll` isn't part of the interface on purpose.

**Comment by Bilge** [comment]
What is the purpose of that?

**Comment by kelunik** [comment]
The interface contains what's required to make `CookieJar` work for the interceptor. Bloating the interface makes other implementations harder and might make certain optimizations impossible.
